# Generated by Django 5.2.4 on 2025-08-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='enlace',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tecnologias',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
